### ISSUE TITLE
Arrows for moving server entry to new list, not properly working with scrolling

### ISSUE THREAD

**Issue by Boy0000** [mrmelon54/multiple_server_lists#1]
When trying to move down my main server list to change one over to another list, the arrows are not following the scrolling.
Thus making it impossible to do  this when having big server lists

https://github.com/mrmelon54/multiple_server_lists/assets/62521371/d99db10b-e310-4215-b7b1-6cae574391f1

**Comment by mrmelon54** [comment]
looks like the arrows line are draw in the correct position

but the hovered item is being detected incorrectly, thus rendering the wrong set of arrows

clicking on the arrows to move servers should still work as clicks are calculated separately
